# DDR constraints for VPK360 LPDDR5X — 4 channels: C0, C1, C4, C5
# Each channel: 32-bit CH0 interface, LPDDR5X-8533 @ 320 MHz sys_clk
# IOSTANDARD / SLEW / OUTPUT_IMPEDANCE values from board design requirements

# DDRMC5E site LOC constraints — fixes each single-MC NOC to the correct channel.
# Without these, Vivado auto-places all 4 NOC instances at the same site, causing
# MIG "port locations changed" errors on CA/CK/CS (which are fixed per-site pins).
# Site-to-channel mapping: DDRMC5E_XnY0 → channel n (confirmed from working impl).
# Absolute path - the BD instance name (cpm6_cxl_ep_brg_i) is fixed by this CED's
# own design.xml/xitem.json registration for every invocation path (GUI and
# console), not user-editable, so this applies identically across all combos.
set_property LOC DDRMC5E_X0Y0 [get_cells {cpm6_cxl_ep_brg_i/axi_noc2_c0/inst/MC0_ddrc/inst/noc_ddr5_phy/inst/DDRMC5_COMP}]
set_property LOC DDRMC5E_X1Y0 [get_cells {cpm6_cxl_ep_brg_i/axi_noc2_c1/inst/MC0_ddrc/inst/noc_ddr5_phy/inst/DDRMC5_COMP}]
set_property LOC DDRMC5E_X4Y0 [get_cells {cpm6_cxl_ep_brg_i/axi_noc2_c4/inst/MC0_ddrc/inst/noc_ddr5_phy/inst/DDRMC5_COMP}]
set_property LOC DDRMC5E_X5Y0 [get_cells {cpm6_cxl_ep_brg_i/axi_noc2_c5/inst/MC0_ddrc/inst/noc_ddr5_phy/inst/DDRMC5_COMP}]

# ── IOSTANDARD / SLEW / OUTPUT_IMPEDANCE ────────────────────────────────────
# C? matches this design's 4 populated channels (C0/C1/C4/C5); reset_n
# has no [0] bit-select since the generated top-level wrapper declares
# *_reset_n as a plain scalar port.

# ── IOSTANDARD ────────────────────────────────────────────────────────────────
# Differential signals: CK, RDQS, WCK
set_property IOSTANDARD DIFF_LVSTL05_10 [get_ports {C?_CH0_LPDDR5_0_ck_* C?_CH0_LPDDR5_0_rdqs_* C?_CH0_LPDDR5_0_wck_*}]
# Single-ended: CS, reset_n → LVCMOS10
set_property IOSTANDARD LVCMOS10 [get_ports {C?_CH0_LPDDR5_0_cs[*] C?_CH0_LPDDR5_0_reset_n}]
# CA, DQ, DMI → LVSTL05_10
set_property IOSTANDARD LVSTL05_10 [get_ports {C?_CH0_LPDDR5_0_ca[*] C?_CH0_LPDDR5_0_dmi[*] C?_CH0_LPDDR5_0_dq[*]}]

# Sys clocks: LVDS12 (2 physical oscillators, each shared by 2 DDRMC channels via util_ds_buf)
set_property IOSTANDARD LVDS12 [get_ports {sys_clk0_0_clk_p}]
set_property IOSTANDARD LVDS12 [get_ports {sys_clk4_0_clk_p}]

# ── SLEW ──────────────────────────────────────────────────────────────────────
set_property SLEW FAST [get_ports {C?_CH0_LPDDR5_0_ca[*] C?_CH0_LPDDR5_0_ck_* C?_CH0_LPDDR5_0_cs[*] C?_CH0_LPDDR5_0_dmi[*] C?_CH0_LPDDR5_0_dq[*] C?_CH0_LPDDR5_0_reset_n C?_CH0_LPDDR5_0_wck_*}]

# ── OUTPUT_IMPEDANCE ──────────────────────────────────────────────────────────
set_property OUTPUT_IMPEDANCE RDRV_40_40 [get_ports {C?_CH0_LPDDR5_0_ca[*] C?_CH0_LPDDR5_0_ck_* C?_CH0_LPDDR5_0_dmi[*] C?_CH0_LPDDR5_0_dq[*] C?_CH0_LPDDR5_0_wck_*}]


# ── C0 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN AN6  [get_ports {C0_CH0_LPDDR5_0_dq[3]}]
set_property PACKAGE_PIN AN7  [get_ports {C0_CH0_LPDDR5_0_dq[1]}]
set_property PACKAGE_PIN AN9  [get_ports {C0_CH0_LPDDR5_0_wck_t[0]}]
set_property PACKAGE_PIN AP7  [get_ports {C0_CH0_LPDDR5_0_dq[0]}]
set_property PACKAGE_PIN AP8  [get_ports {C0_CH0_LPDDR5_0_wck_c[0]}]
set_property PACKAGE_PIN AR6  [get_ports {C0_CH0_LPDDR5_0_dq[5]}]
set_property PACKAGE_PIN AR8  [get_ports {C0_CH0_LPDDR5_0_dmi[0]}]
set_property PACKAGE_PIN AR9  [get_ports {C0_CH0_LPDDR5_0_dq[2]}]
set_property PACKAGE_PIN AT6  [get_ports {C0_CH0_LPDDR5_0_rdqs_c[0]}]
set_property PACKAGE_PIN AT9  [get_ports {C0_CH0_LPDDR5_0_dq[7]}]
set_property PACKAGE_PIN AU7  [get_ports {C0_CH0_LPDDR5_0_rdqs_t[0]}]
set_property PACKAGE_PIN AU8  [get_ports {C0_CH0_LPDDR5_0_dq[4]}]
set_property PACKAGE_PIN AV8  [get_ports {C0_CH0_LPDDR5_0_wck_c[1]}]
set_property PACKAGE_PIN AV9  [get_ports {C0_CH0_LPDDR5_0_dq[6]}]
set_property PACKAGE_PIN AV11 [get_ports {C0_CH0_LPDDR5_0_dq[15]}]
set_property PACKAGE_PIN AW7  [get_ports {C0_CH0_LPDDR5_0_dq[12]}]
set_property PACKAGE_PIN AW9  [get_ports {C0_CH0_LPDDR5_0_wck_t[1]}]
set_property PACKAGE_PIN AW10 [get_ports {C0_CH0_LPDDR5_0_dq[14]}]
set_property PACKAGE_PIN AY7  [get_ports {C0_CH0_LPDDR5_0_dq[11]}]
set_property PACKAGE_PIN AY8  [get_ports {C0_CH0_LPDDR5_0_dq[13]}]
set_property PACKAGE_PIN AY11 [get_ports {C0_CH0_LPDDR5_0_dmi[1]}]
set_property PACKAGE_PIN BA8  [get_ports {C0_CH0_LPDDR5_0_rdqs_c[1]}]
set_property PACKAGE_PIN BA9  [get_ports {C0_CH0_LPDDR5_0_dq[9]}]
set_property PACKAGE_PIN BA11 [get_ports {C0_CH0_LPDDR5_0_dq[10]}]
set_property PACKAGE_PIN BB9  [get_ports {C0_CH0_LPDDR5_0_rdqs_t[1]}]
set_property PACKAGE_PIN BB10 [get_ports {C0_CH0_LPDDR5_0_dq[8]}]
set_property PACKAGE_PIN AN1  [get_ports {C0_CH0_LPDDR5_0_dq[24]}]
set_property PACKAGE_PIN AN3  [get_ports {C0_CH0_LPDDR5_0_dq[25]}]
set_property PACKAGE_PIN AN4  [get_ports {C0_CH0_LPDDR5_0_dq[27]}]
set_property PACKAGE_PIN AP1  [get_ports {C0_CH0_LPDDR5_0_wck_c[3]}]
set_property PACKAGE_PIN AP2  [get_ports {C0_CH0_LPDDR5_0_dq[26]}]
set_property PACKAGE_PIN AP4  [get_ports {C0_CH0_LPDDR5_0_rdqs_c[3]}]
set_property PACKAGE_PIN AP5  [get_ports {C0_CH0_LPDDR5_0_rdqs_t[3]}]
set_property PACKAGE_PIN AR2  [get_ports {C0_CH0_LPDDR5_0_wck_t[3]}]
set_property PACKAGE_PIN AR3  [get_ports {C0_CH0_LPDDR5_0_dq[31]}]
set_property PACKAGE_PIN AT3  [get_ports {C0_CH0_LPDDR5_0_dq[30]}]
set_property PACKAGE_PIN AU1  [get_ports {C0_CH0_LPDDR5_0_dq[19]}]
set_property PACKAGE_PIN AU2  [get_ports {C0_CH0_LPDDR5_0_dmi[3]}]
set_property PACKAGE_PIN AU4  [get_ports {C0_CH0_LPDDR5_0_dq[29]}]
set_property PACKAGE_PIN AU5  [get_ports {C0_CH0_LPDDR5_0_dq[28]}]
set_property PACKAGE_PIN AV2  [get_ports {C0_CH0_LPDDR5_0_dq[18]}]
set_property PACKAGE_PIN AV3  [get_ports {C0_CH0_LPDDR5_0_rdqs_t[2]}]
set_property PACKAGE_PIN AV5  [get_ports {C0_CH0_LPDDR5_0_dq[22]}]
set_property PACKAGE_PIN AW1  [get_ports {C0_CH0_LPDDR5_0_dq[17]}]
set_property PACKAGE_PIN AW3  [get_ports {C0_CH0_LPDDR5_0_rdqs_c[2]}]
set_property PACKAGE_PIN AW4  [get_ports {C0_CH0_LPDDR5_0_dq[23]}]
set_property PACKAGE_PIN AY1  [get_ports {C0_CH0_LPDDR5_0_wck_c[2]}]
set_property PACKAGE_PIN AY2  [get_ports {C0_CH0_LPDDR5_0_dq[16]}]
set_property PACKAGE_PIN AY5  [get_ports {C0_CH0_LPDDR5_0_dmi[2]}]
set_property PACKAGE_PIN BA2  [get_ports {C0_CH0_LPDDR5_0_wck_t[2]}]
set_property PACKAGE_PIN BA5  [get_ports {C0_CH0_LPDDR5_0_dq[20]}]
set_property PACKAGE_PIN BB6  [get_ports {C0_CH0_LPDDR5_0_dq[21]}]
set_property PACKAGE_PIN BE9  [get_ports {sys_clk0_0_clk_p}]
set_property PACKAGE_PIN BF8  [get_ports {sys_clk0_0_clk_n}]

# ── C1 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN BG2  [get_ports {C1_CH0_LPDDR5_0_dq[28]}]
set_property PACKAGE_PIN BG3  [get_ports {C1_CH0_LPDDR5_0_dq[29]}]
set_property PACKAGE_PIN BG5  [get_ports {C1_CH0_LPDDR5_0_dq[27]}]
set_property PACKAGE_PIN BH1  [get_ports {C1_CH0_LPDDR5_0_rdqs_t[3]}]
set_property PACKAGE_PIN BH3  [get_ports {C1_CH0_LPDDR5_0_wck_t[3]}]
set_property PACKAGE_PIN BH4  [get_ports {C1_CH0_LPDDR5_0_dq[24]}]
set_property PACKAGE_PIN BJ1  [get_ports {C1_CH0_LPDDR5_0_rdqs_c[3]}]
set_property PACKAGE_PIN BJ2  [get_ports {C1_CH0_LPDDR5_0_wck_c[3]}]
set_property PACKAGE_PIN BJ4  [get_ports {C1_CH0_LPDDR5_0_dq[30]}]
set_property PACKAGE_PIN BJ5  [get_ports {C1_CH0_LPDDR5_0_dmi[3]}]
set_property PACKAGE_PIN BK2  [get_ports {C1_CH0_LPDDR5_0_dq[25]}]
set_property PACKAGE_PIN BK3  [get_ports {C1_CH0_LPDDR5_0_dq[31]}]
set_property PACKAGE_PIN BL1  [get_ports {C1_CH0_LPDDR5_0_dq[26]}]
set_property PACKAGE_PIN BM1  [get_ports {C1_CH0_LPDDR5_0_rdqs_c[2]}]
set_property PACKAGE_PIN BM2  [get_ports {C1_CH0_LPDDR5_0_dq[21]}]
set_property PACKAGE_PIN BN2  [get_ports {C1_CH0_LPDDR5_0_rdqs_t[2]}]
set_property PACKAGE_PIN BN3  [get_ports {C1_CH0_LPDDR5_0_dq[20]}]
set_property PACKAGE_PIN BP1  [get_ports {C1_CH0_LPDDR5_0_dq[22]}]
set_property PACKAGE_PIN BP4  [get_ports {C1_CH0_LPDDR5_0_dmi[2]}]
set_property PACKAGE_PIN BR2  [get_ports {C1_CH0_LPDDR5_0_dq[23]}]
set_property PACKAGE_PIN BR4  [get_ports {C1_CH0_LPDDR5_0_dq[19]}]
set_property PACKAGE_PIN BR5  [get_ports {C1_CH0_LPDDR5_0_dq[18]}]
set_property PACKAGE_PIN BT3  [get_ports {C1_CH0_LPDDR5_0_dq[17]}]
set_property PACKAGE_PIN BT5  [get_ports {C1_CH0_LPDDR5_0_dq[16]}]
set_property PACKAGE_PIN BU4  [get_ports {C1_CH0_LPDDR5_0_wck_c[2]}]
set_property PACKAGE_PIN BV5  [get_ports {C1_CH0_LPDDR5_0_wck_t[2]}]
set_property PACKAGE_PIN BG6  [get_ports {C1_CH0_LPDDR5_0_dq[2]}]
set_property PACKAGE_PIN BG8  [get_ports {C1_CH0_LPDDR5_0_rdqs_c[0]}]
set_property PACKAGE_PIN BG9  [get_ports {C1_CH0_LPDDR5_0_rdqs_t[0]}]
set_property PACKAGE_PIN BH6  [get_ports {C1_CH0_LPDDR5_0_wck_c[0]}]
set_property PACKAGE_PIN BH7  [get_ports {C1_CH0_LPDDR5_0_dq[7]}]
set_property PACKAGE_PIN BH9  [get_ports {C1_CH0_LPDDR5_0_dq[6]}]
set_property PACKAGE_PIN BJ7  [get_ports {C1_CH0_LPDDR5_0_wck_t[0]}]
set_property PACKAGE_PIN BJ8  [get_ports {C1_CH0_LPDDR5_0_dq[0]}]
set_property PACKAGE_PIN BK6  [get_ports {C1_CH0_LPDDR5_0_dq[1]}]
set_property PACKAGE_PIN BK9  [get_ports {C1_CH0_LPDDR5_0_dq[4]}]
set_property PACKAGE_PIN BL6  [get_ports {C1_CH0_LPDDR5_0_dq[3]}]
set_property PACKAGE_PIN BL7  [get_ports {C1_CH0_LPDDR5_0_dq[14]}]
set_property PACKAGE_PIN BL9  [get_ports {C1_CH0_LPDDR5_0_dmi[0]}]
set_property PACKAGE_PIN BL10 [get_ports {C1_CH0_LPDDR5_0_dq[5]}]
set_property PACKAGE_PIN BM7  [get_ports {C1_CH0_LPDDR5_0_rdqs_t[1]}]
set_property PACKAGE_PIN BM8  [get_ports {C1_CH0_LPDDR5_0_dq[15]}]
set_property PACKAGE_PIN BN5  [get_ports {C1_CH0_LPDDR5_0_dq[13]}]
set_property PACKAGE_PIN BN6  [get_ports {C1_CH0_LPDDR5_0_rdqs_c[1]}]
set_property PACKAGE_PIN BP6  [get_ports {C1_CH0_LPDDR5_0_dq[12]}]
set_property PACKAGE_PIN BR7  [get_ports {C1_CH0_LPDDR5_0_dq[10]}]
set_property PACKAGE_PIN BR8  [get_ports {C1_CH0_LPDDR5_0_dmi[1]}]
set_property PACKAGE_PIN BT6  [get_ports {C1_CH0_LPDDR5_0_wck_c[1]}]
set_property PACKAGE_PIN BT8  [get_ports {C1_CH0_LPDDR5_0_dq[8]}]
set_property PACKAGE_PIN BU6  [get_ports {C1_CH0_LPDDR5_0_dq[11]}]
set_property PACKAGE_PIN BU7  [get_ports {C1_CH0_LPDDR5_0_wck_t[1]}]
set_property PACKAGE_PIN BV7  [get_ports {C1_CH0_LPDDR5_0_dq[9]}]

# ── C4 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN BK27 [get_ports {C4_CH0_LPDDR5_0_dq[25]}]
set_property PACKAGE_PIN BK29 [get_ports {C4_CH0_LPDDR5_0_dq[27]}]
set_property PACKAGE_PIN BK30 [get_ports {C4_CH0_LPDDR5_0_dq[26]}]
set_property PACKAGE_PIN BL27 [get_ports {C4_CH0_LPDDR5_0_dq[24]}]
set_property PACKAGE_PIN BL28 [get_ports {C4_CH0_LPDDR5_0_wck_t[3]}]
set_property PACKAGE_PIN BL30 [get_ports {C4_CH0_LPDDR5_0_dmi[3]}]
set_property PACKAGE_PIN BL31 [get_ports {C4_CH0_LPDDR5_0_dq[29]}]
set_property PACKAGE_PIN BM28 [get_ports {C4_CH0_LPDDR5_0_wck_c[3]}]
set_property PACKAGE_PIN BM29 [get_ports {C4_CH0_LPDDR5_0_dq[31]}]
set_property PACKAGE_PIN BM32 [get_ports {C4_CH0_LPDDR5_0_dq[28]}]
set_property PACKAGE_PIN BN29 [get_ports {C4_CH0_LPDDR5_0_dq[30]}]
set_property PACKAGE_PIN BN30 [get_ports {C4_CH0_LPDDR5_0_rdqs_t[3]}]
set_property PACKAGE_PIN BP28 [get_ports {C4_CH0_LPDDR5_0_wck_t[2]}]
set_property PACKAGE_PIN BP30 [get_ports {C4_CH0_LPDDR5_0_rdqs_c[3]}]
set_property PACKAGE_PIN BR28 [get_ports {C4_CH0_LPDDR5_0_wck_c[2]}]
set_property PACKAGE_PIN BR29 [get_ports {C4_CH0_LPDDR5_0_dq[18]}]
set_property PACKAGE_PIN BR31 [get_ports {C4_CH0_LPDDR5_0_dq[22]}]
set_property PACKAGE_PIN BR32 [get_ports {C4_CH0_LPDDR5_0_dq[21]}]
set_property PACKAGE_PIN BT29 [get_ports {C4_CH0_LPDDR5_0_dq[16]}]
set_property PACKAGE_PIN BT32 [get_ports {C4_CH0_LPDDR5_0_dmi[2]}]
set_property PACKAGE_PIN BU28 [get_ports {C4_CH0_LPDDR5_0_rdqs_t[2]}]
set_property PACKAGE_PIN BU30 [get_ports {C4_CH0_LPDDR5_0_dq[19]}]
set_property PACKAGE_PIN BV28 [get_ports {C4_CH0_LPDDR5_0_rdqs_c[2]}]
set_property PACKAGE_PIN BV29 [get_ports {C4_CH0_LPDDR5_0_dq[17]}]
set_property PACKAGE_PIN BV31 [get_ports {C4_CH0_LPDDR5_0_dq[20]}]
set_property PACKAGE_PIN BV32 [get_ports {C4_CH0_LPDDR5_0_dq[23]}]
set_property PACKAGE_PIN BB27 [get_ports {C4_CH0_LPDDR5_0_dq[14]}]
set_property PACKAGE_PIN BB28 [get_ports {C4_CH0_LPDDR5_0_dq[15]}]
set_property PACKAGE_PIN BB30 [get_ports {C4_CH0_LPDDR5_0_rdqs_t[1]}]
set_property PACKAGE_PIN BB31 [get_ports {C4_CH0_LPDDR5_0_rdqs_c[1]}]
set_property PACKAGE_PIN BB33 [get_ports {C4_CH0_LPDDR5_0_dq[8]}]
set_property PACKAGE_PIN BC29 [get_ports {C4_CH0_LPDDR5_0_dq[13]}]
set_property PACKAGE_PIN BC34 [get_ports {C4_CH0_LPDDR5_0_dq[11]}]
set_property PACKAGE_PIN BD29 [get_ports {C4_CH0_LPDDR5_0_dq[12]}]
set_property PACKAGE_PIN BD32 [get_ports {C4_CH0_LPDDR5_0_dq[10]}]
set_property PACKAGE_PIN BE31 [get_ports {C4_CH0_LPDDR5_0_dq[9]}]
set_property PACKAGE_PIN BF29 [get_ports {C4_CH0_LPDDR5_0_dq[3]}]
set_property PACKAGE_PIN BF31 [get_ports {C4_CH0_LPDDR5_0_dmi[1]}]
set_property PACKAGE_PIN BF32 [get_ports {C4_CH0_LPDDR5_0_rdqs_t[0]}]
set_property PACKAGE_PIN BG27 [get_ports {C4_CH0_LPDDR5_0_wck_t[1]}]
set_property PACKAGE_PIN BG29 [get_ports {C4_CH0_LPDDR5_0_dq[1]}]
set_property PACKAGE_PIN BG32 [get_ports {C4_CH0_LPDDR5_0_rdqs_c[0]}]
set_property PACKAGE_PIN BG33 [get_ports {C4_CH0_LPDDR5_0_dq[2]}]
set_property PACKAGE_PIN BH27 [get_ports {C4_CH0_LPDDR5_0_wck_c[1]}]
set_property PACKAGE_PIN BH28 [get_ports {C4_CH0_LPDDR5_0_dq[4]}]
set_property PACKAGE_PIN BH31 [get_ports {C4_CH0_LPDDR5_0_dq[0]}]
set_property PACKAGE_PIN BH33 [get_ports {C4_CH0_LPDDR5_0_dq[7]}]
set_property PACKAGE_PIN BJ28 [get_ports {C4_CH0_LPDDR5_0_dq[5]}]
set_property PACKAGE_PIN BJ31 [get_ports {C4_CH0_LPDDR5_0_dq[6]}]
set_property PACKAGE_PIN BJ32 [get_ports {C4_CH0_LPDDR5_0_wck_t[0]}]
set_property PACKAGE_PIN BK32 [get_ports {C4_CH0_LPDDR5_0_wck_c[0]}]
set_property PACKAGE_PIN BK33 [get_ports {C4_CH0_LPDDR5_0_dmi[0]}]
set_property PACKAGE_PIN BU36 [get_ports {sys_clk4_0_clk_p}]
set_property PACKAGE_PIN BV37 [get_ports {sys_clk4_0_clk_n}]

# ── C5 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN BL39 [get_ports {C5_CH0_LPDDR5_0_dmi[2]}]
set_property PACKAGE_PIN BL40 [get_ports {C5_CH0_LPDDR5_0_dq[20]}]
set_property PACKAGE_PIN BL42 [get_ports {C5_CH0_LPDDR5_0_rdqs_t[2]}]
set_property PACKAGE_PIN BL43 [get_ports {C5_CH0_LPDDR5_0_dq[17]}]
set_property PACKAGE_PIN BM40 [get_ports {C5_CH0_LPDDR5_0_dq[23]}]
set_property PACKAGE_PIN BM41 [get_ports {C5_CH0_LPDDR5_0_rdqs_c[2]}]
set_property PACKAGE_PIN BM43 [get_ports {C5_CH0_LPDDR5_0_dq[16]}]
set_property PACKAGE_PIN BN38 [get_ports {C5_CH0_LPDDR5_0_dq[21]}]
set_property PACKAGE_PIN BN39 [get_ports {C5_CH0_LPDDR5_0_wck_t[2]}]
set_property PACKAGE_PIN BN41 [get_ports {C5_CH0_LPDDR5_0_dq[19]}]
set_property PACKAGE_PIN BP39 [get_ports {C5_CH0_LPDDR5_0_dq[22]}]
set_property PACKAGE_PIN BP40 [get_ports {C5_CH0_LPDDR5_0_wck_c[2]}]
set_property PACKAGE_PIN BP42 [get_ports {C5_CH0_LPDDR5_0_dq[18]}]
set_property PACKAGE_PIN BR38 [get_ports {C5_CH0_LPDDR5_0_dmi[3]}]
set_property PACKAGE_PIN BR40 [get_ports {C5_CH0_LPDDR5_0_dq[26]}]
set_property PACKAGE_PIN BR41 [get_ports {C5_CH0_LPDDR5_0_rdqs_t[3]}]
set_property PACKAGE_PIN BR43 [get_ports {C5_CH0_LPDDR5_0_dq[29]}]
set_property PACKAGE_PIN BT39 [get_ports {C5_CH0_LPDDR5_0_dq[25]}]
set_property PACKAGE_PIN BT41 [get_ports {C5_CH0_LPDDR5_0_rdqs_c[3]}]
set_property PACKAGE_PIN BT42 [get_ports {C5_CH0_LPDDR5_0_dq[28]}]
set_property PACKAGE_PIN BU39 [get_ports {C5_CH0_LPDDR5_0_dq[24]}]
set_property PACKAGE_PIN BU40 [get_ports {C5_CH0_LPDDR5_0_wck_t[3]}]
set_property PACKAGE_PIN BU42 [get_ports {C5_CH0_LPDDR5_0_dq[30]}]
set_property PACKAGE_PIN BV38 [get_ports {C5_CH0_LPDDR5_0_dq[27]}]
set_property PACKAGE_PIN BV40 [get_ports {C5_CH0_LPDDR5_0_wck_c[3]}]
set_property PACKAGE_PIN BV41 [get_ports {C5_CH0_LPDDR5_0_dq[31]}]
set_property PACKAGE_PIN AY41 [get_ports {C5_CH0_LPDDR5_0_wck_t[0]}]
set_property PACKAGE_PIN BA39 [get_ports {C5_CH0_LPDDR5_0_dq[2]}]
set_property PACKAGE_PIN BA41 [get_ports {C5_CH0_LPDDR5_0_wck_c[0]}]
set_property PACKAGE_PIN BA42 [get_ports {C5_CH0_LPDDR5_0_dq[7]}]
set_property PACKAGE_PIN BB39 [get_ports {C5_CH0_LPDDR5_0_dq[3]}]
set_property PACKAGE_PIN BB40 [get_ports {C5_CH0_LPDDR5_0_dmi[0]}]
set_property PACKAGE_PIN BB42 [get_ports {C5_CH0_LPDDR5_0_dq[6]}]
set_property PACKAGE_PIN BD39 [get_ports {C5_CH0_LPDDR5_0_dq[0]}]
set_property PACKAGE_PIN BD42 [get_ports {C5_CH0_LPDDR5_0_dq[5]}]
set_property PACKAGE_PIN BE39 [get_ports {C5_CH0_LPDDR5_0_dq[1]}]
set_property PACKAGE_PIN BE42 [get_ports {C5_CH0_LPDDR5_0_dq[4]}]
set_property PACKAGE_PIN BF38 [get_ports {C5_CH0_LPDDR5_0_dq[15]}]
set_property PACKAGE_PIN BF40 [get_ports {C5_CH0_LPDDR5_0_rdqs_t[0]}]
set_property PACKAGE_PIN BF41 [get_ports {C5_CH0_LPDDR5_0_dq[10]}]
set_property PACKAGE_PIN BG38 [get_ports {C5_CH0_LPDDR5_0_dq[14]}]
set_property PACKAGE_PIN BG39 [get_ports {C5_CH0_LPDDR5_0_rdqs_c[0]}]
set_property PACKAGE_PIN BG41 [get_ports {C5_CH0_LPDDR5_0_dq[8]}]
set_property PACKAGE_PIN BH39 [get_ports {C5_CH0_LPDDR5_0_wck_t[1]}]
set_property PACKAGE_PIN BH40 [get_ports {C5_CH0_LPDDR5_0_wck_c[1]}]
set_property PACKAGE_PIN BH42 [get_ports {C5_CH0_LPDDR5_0_dq[11]}]
set_property PACKAGE_PIN BH43 [get_ports {C5_CH0_LPDDR5_0_dmi[1]}]
set_property PACKAGE_PIN BJ38 [get_ports {C5_CH0_LPDDR5_0_rdqs_t[1]}]
set_property PACKAGE_PIN BJ40 [get_ports {C5_CH0_LPDDR5_0_dq[9]}]
set_property PACKAGE_PIN BJ41 [get_ports {C5_CH0_LPDDR5_0_dq[12]}]
set_property PACKAGE_PIN BK38 [get_ports {C5_CH0_LPDDR5_0_rdqs_c[1]}]
set_property PACKAGE_PIN BK39 [get_ports {C5_CH0_LPDDR5_0_dq[13]}]

# ── CA/CK/CS/RESET — from mc_vpx working impl (site-selector pins for DDRMC5E) ──
# MIG uses these to determine which DDRMC5E_XnY0 site to place each controller at.
# ── C0 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN AY4  [get_ports {C0_CH0_LPDDR5_0_ca[0]}]
set_property PACKAGE_PIN BA6  [get_ports {C0_CH0_LPDDR5_0_ca[1]}]
set_property PACKAGE_PIN BB7  [get_ports {C0_CH0_LPDDR5_0_ca[2]}]
set_property PACKAGE_PIN AY10 [get_ports {C0_CH0_LPDDR5_0_ca[3]}]
set_property PACKAGE_PIN AW6  [get_ports {C0_CH0_LPDDR5_0_ca[4]}]
set_property PACKAGE_PIN AV6  [get_ports {C0_CH0_LPDDR5_0_ca[5]}]
set_property PACKAGE_PIN AT7  [get_ports {C0_CH0_LPDDR5_0_ca[6]}]
set_property PACKAGE_PIN BB4  [get_ports {C0_CH0_LPDDR5_0_ck_t[0]}]
set_property PACKAGE_PIN BA3  [get_ports {C0_CH0_LPDDR5_0_ck_c[0]}]
set_property PACKAGE_PIN AR5  [get_ports {C0_CH0_LPDDR5_0_cs[0]}]
set_property PACKAGE_PIN AT4  [get_ports {C0_CH0_LPDDR5_0_cs[1]}]
set_property PACKAGE_PIN AT1  [get_ports {C0_CH0_LPDDR5_0_reset_n}]
# ── C1 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN BP3  [get_ports {C1_CH0_LPDDR5_0_ca[0]}]
set_property PACKAGE_PIN BJ10 [get_ports {C1_CH0_LPDDR5_0_ca[1]}]
set_property PACKAGE_PIN BH10 [get_ports {C1_CH0_LPDDR5_0_ca[2]}]
set_property PACKAGE_PIN BK8  [get_ports {C1_CH0_LPDDR5_0_ca[3]}]
set_property PACKAGE_PIN BN8  [get_ports {C1_CH0_LPDDR5_0_ca[4]}]
set_property PACKAGE_PIN BP9  [get_ports {C1_CH0_LPDDR5_0_ca[5]}]
set_property PACKAGE_PIN BP7  [get_ports {C1_CH0_LPDDR5_0_ca[6]}]
set_property PACKAGE_PIN BM5  [get_ports {C1_CH0_LPDDR5_0_ck_t[0]}]
set_property PACKAGE_PIN BM4  [get_ports {C1_CH0_LPDDR5_0_ck_c[0]}]
set_property PACKAGE_PIN BL4  [get_ports {C1_CH0_LPDDR5_0_cs[0]}]
set_property PACKAGE_PIN BL3  [get_ports {C1_CH0_LPDDR5_0_cs[1]}]
set_property PACKAGE_PIN BK5  [get_ports {C1_CH0_LPDDR5_0_reset_n}]
# ── C4 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN BL33 [get_ports {C4_CH0_LPDDR5_0_ca[0]}]
set_property PACKAGE_PIN BU31 [get_ports {C4_CH0_LPDDR5_0_ca[1]}]
set_property PACKAGE_PIN BT30 [get_ports {C4_CH0_LPDDR5_0_ca[2]}]
set_property PACKAGE_PIN BT33 [get_ports {C4_CH0_LPDDR5_0_ca[3]}]
set_property PACKAGE_PIN BP31 [get_ports {C4_CH0_LPDDR5_0_ca[4]}]
set_property PACKAGE_PIN BN32 [get_ports {C4_CH0_LPDDR5_0_ca[5]}]
set_property PACKAGE_PIN BM31 [get_ports {C4_CH0_LPDDR5_0_ca[6]}]
set_property PACKAGE_PIN BH30 [get_ports {C4_CH0_LPDDR5_0_ck_t[0]}]
set_property PACKAGE_PIN BJ29 [get_ports {C4_CH0_LPDDR5_0_ck_c[0]}]
set_property PACKAGE_PIN BE27 [get_ports {C4_CH0_LPDDR5_0_cs[0]}]
set_property PACKAGE_PIN BF28 [get_ports {C4_CH0_LPDDR5_0_cs[1]}]
set_property PACKAGE_PIN BG30 [get_ports {C4_CH0_LPDDR5_0_reset_n}]
# ── C5 ──────────────────────────────────────────────────────────────────────
set_property PACKAGE_PIN BT38 [get_ports {C5_CH0_LPDDR5_0_ca[0]}]
set_property PACKAGE_PIN BK42 [get_ports {C5_CH0_LPDDR5_0_ca[1]}]
set_property PACKAGE_PIN BK41 [get_ports {C5_CH0_LPDDR5_0_ca[2]}]
set_property PACKAGE_PIN BJ43 [get_ports {C5_CH0_LPDDR5_0_ca[3]}]
set_property PACKAGE_PIN BG42 [get_ports {C5_CH0_LPDDR5_0_ca[4]}]
set_property PACKAGE_PIN BF43 [get_ports {C5_CH0_LPDDR5_0_ca[5]}]
set_property PACKAGE_PIN BC41 [get_ports {C5_CH0_LPDDR5_0_ca[6]}]
set_property PACKAGE_PIN BU43 [get_ports {C5_CH0_LPDDR5_0_ck_t[0]}]
set_property PACKAGE_PIN BV43 [get_ports {C5_CH0_LPDDR5_0_ck_c[0]}]
set_property PACKAGE_PIN BN42 [get_ports {C5_CH0_LPDDR5_0_cs[0]}]
set_property PACKAGE_PIN BP43 [get_ports {C5_CH0_LPDDR5_0_cs[1]}]
set_property PACKAGE_PIN BM38 [get_ports {C5_CH0_LPDDR5_0_reset_n}]
