///////////////////////////////////////////////////////////////////////////////
//   ____  ____ 
//  /   /\/   /
// /___/  \  /    Vendor: Xilinx
// \   \   \/     Version : 1.5
//  \   \         Application : 7 Series FPGAs Transceivers Wizard
//  /   /         Filename : rocketio_wrapper_tile.v
// /___/   /\     
// \   \  /  \ 
//  \___\/\___\
//
//
// Module ROCKETIO_WRAPPER_TILE (a GT Wrapper)
// Generated by Xilinx 7 Series FPGAs Transceivers Wizard
// 
// 
// (c) Copyright 2010-2011 Xilinx, Inc. All rights reserved.
// 
// This file contains confidential and proprietary information
// of Xilinx, Inc. and is protected under U.S. and
// international copyright and other intellectual property
// laws.
// 
// DISCLAIMER
// This disclaimer is not a license and does not grant any
// rights to the materials distributed herewith. Except as
// otherwise provided in a valid license issued to you by
// Xilinx, and to the maximum extent permitted by applicable
// law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
// WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
// AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
// BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
// INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
// (2) Xilinx shall not be liable (whether in contract or tort,
// including negligence, or under any other theory of
// liability) for any loss or damage of any kind or nature
// related to, arising under or in connection with these
// materials, including for any direct, or any indirect,
// special, incidental, or consequential loss or damage
// (including loss of data, profits, goodwill, or any type of
// loss or damage suffered as a result of any action brought
// by a third party) even if such damage or loss was
// reasonably foreseeable or Xilinx had been advised of the
// possibility of the same.
// 
// CRITICAL APPLICATIONS
// Xilinx products are not designed or intended to be fail-
// safe, or for use in any application requiring fail-safe
// performance, such as life-support or safety devices or
// systems, Class III medical devices, nuclear facilities,
// applications related to the deployment of airbags, or any
// other applications that could lead to death, personal
// injury, or severe property or environmental damage
// (individually and collectively, "Critical
// Applications"). Customer assumes the sole risk and
// liability of any use of Xilinx products in Critical
// Applications, subject only to applicable laws and
// regulations governing limitations on product liability.
// 
// THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
// PART OF THIS FILE AT ALL TIMES. 


`timescale 1ns / 1ps
`define DLY #1

//***************************** Entity Declaration ****************************

(* CORE_GENERATION_INFO = "ROCKETIO_WRAPPER_TILE,gtwizard_v1_5,{protocol_file=gigabit_ethernet}" *) module ROCKETIO_WRAPPER_TILE #
(
    // Simulation attributes
    parameter   WRAPPER_SIM_GTRESET_SPEEDUP    = "false"    // Set to "true" to speed up sim reset
)
(
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT0  (X0Y0)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT0_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT0_CPLLFBCLKLOST_OUT,
    output          GT0_CPLLLOCK_OUT,
    input           GT0_CPLLLOCKDETCLK_IN,
    output          GT0_CPLLREFCLKLOST_OUT,
    input           GT0_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT0_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT0_LOOPBACK_IN,
    input   [1:0]   GT0_RXPD_IN,
    input   [1:0]   GT0_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT0_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT0_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT0_RXBYTEISALIGNED_OUT,
    output          GT0_RXBYTEREALIGN_OUT,
    output          GT0_RXCOMMADET_OUT,
    input           GT0_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT0_GTRXRESET_IN,
    output  [15:0]  GT0_RXDATA_OUT,
    output          GT0_RXOUTCLK_OUT,
    input           GT0_RXPCSRESET_IN,
    input           GT0_RXUSRCLK_IN,
    input           GT0_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT0_GTXRXN_IN,
    input           GT0_GTXRXP_IN,
    output          GT0_RXCDRLOCK_OUT,
    output          GT0_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT0_RXBUFRESET_IN,
    output  [2:0]   GT0_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT0_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT0_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT0_TXPRECURSORINV_IN,
    input           GT0_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT0_GTTXRESET_IN,
    input   [15:0]  GT0_TXDATA_IN,
    output          GT0_TXOUTCLK_OUT,
    output          GT0_TXOUTCLKFABRIC_OUT,
    output          GT0_TXOUTCLKPCS_OUT,
    input           GT0_TXPCSRESET_IN,
    input           GT0_TXUSRCLK_IN,
    input           GT0_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT0_GTXTXN_OUT,
    output          GT0_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT0_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT0_TXRESETDONE_OUT,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT1  (X0Y1)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT1_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT1_CPLLFBCLKLOST_OUT,
    output          GT1_CPLLLOCK_OUT,
    input           GT1_CPLLLOCKDETCLK_IN,
    output          GT1_CPLLREFCLKLOST_OUT,
    input           GT1_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT1_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT1_LOOPBACK_IN,
    input   [1:0]   GT1_RXPD_IN,
    input   [1:0]   GT1_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT1_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT1_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT1_RXBYTEISALIGNED_OUT,
    output          GT1_RXBYTEREALIGN_OUT,
    output          GT1_RXCOMMADET_OUT,
    input           GT1_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT1_GTRXRESET_IN,
    output  [15:0]  GT1_RXDATA_OUT,
    output          GT1_RXOUTCLK_OUT,
    input           GT1_RXPCSRESET_IN,
    input           GT1_RXUSRCLK_IN,
    input           GT1_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT1_GTXRXN_IN,
    input           GT1_GTXRXP_IN,
    output          GT1_RXCDRLOCK_OUT,
    output          GT1_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT1_RXBUFRESET_IN,
    output  [2:0]   GT1_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT1_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT1_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT1_TXPRECURSORINV_IN,
    input           GT1_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT1_GTTXRESET_IN,
    input   [15:0]  GT1_TXDATA_IN,
    output          GT1_TXOUTCLK_OUT,
    output          GT1_TXOUTCLKFABRIC_OUT,
    output          GT1_TXOUTCLKPCS_OUT,
    input           GT1_TXPCSRESET_IN,
    input           GT1_TXUSRCLK_IN,
    input           GT1_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT1_GTXTXN_OUT,
    output          GT1_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT1_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT1_TXRESETDONE_OUT,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT2  (X0Y2)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT2_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT2_CPLLFBCLKLOST_OUT,
    output          GT2_CPLLLOCK_OUT,
    input           GT2_CPLLLOCKDETCLK_IN,
    output          GT2_CPLLREFCLKLOST_OUT,
    input           GT2_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT2_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT2_LOOPBACK_IN,
    input   [1:0]   GT2_RXPD_IN,
    input   [1:0]   GT2_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT2_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT2_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT2_RXBYTEISALIGNED_OUT,
    output          GT2_RXBYTEREALIGN_OUT,
    output          GT2_RXCOMMADET_OUT,
    input           GT2_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT2_GTRXRESET_IN,
    output  [15:0]  GT2_RXDATA_OUT,
    output          GT2_RXOUTCLK_OUT,
    input           GT2_RXPCSRESET_IN,
    input           GT2_RXUSRCLK_IN,
    input           GT2_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT2_GTXRXN_IN,
    input           GT2_GTXRXP_IN,
    output          GT2_RXCDRLOCK_OUT,
    output          GT2_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT2_RXBUFRESET_IN,
    output  [2:0]   GT2_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT2_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT2_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT2_TXPRECURSORINV_IN,
    input           GT2_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT2_GTTXRESET_IN,
    input   [15:0]  GT2_TXDATA_IN,
    output          GT2_TXOUTCLK_OUT,
    output          GT2_TXOUTCLKFABRIC_OUT,
    output          GT2_TXOUTCLKPCS_OUT,
    input           GT2_TXPCSRESET_IN,
    input           GT2_TXUSRCLK_IN,
    input           GT2_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT2_GTXTXN_OUT,
    output          GT2_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT2_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT2_TXRESETDONE_OUT,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT3  (X0Y3)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT3_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT3_CPLLFBCLKLOST_OUT,
    output          GT3_CPLLLOCK_OUT,
    input           GT3_CPLLLOCKDETCLK_IN,
    output          GT3_CPLLREFCLKLOST_OUT,
    input           GT3_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT3_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT3_LOOPBACK_IN,
    input   [1:0]   GT3_RXPD_IN,
    input   [1:0]   GT3_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT3_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT3_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT3_RXBYTEISALIGNED_OUT,
    output          GT3_RXBYTEREALIGN_OUT,
    output          GT3_RXCOMMADET_OUT,
    input           GT3_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT3_GTRXRESET_IN,
    output  [15:0]  GT3_RXDATA_OUT,
    output          GT3_RXOUTCLK_OUT,
    input           GT3_RXPCSRESET_IN,
    input           GT3_RXUSRCLK_IN,
    input           GT3_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT3_GTXRXN_IN,
    input           GT3_GTXRXP_IN,
    output          GT3_RXCDRLOCK_OUT,
    output          GT3_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT3_RXBUFRESET_IN,
    output  [2:0]   GT3_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT3_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT3_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT3_TXPRECURSORINV_IN,
    input           GT3_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT3_GTTXRESET_IN,
    input   [15:0]  GT3_TXDATA_IN,
    output          GT3_TXOUTCLK_OUT,
    output          GT3_TXOUTCLKFABRIC_OUT,
    output          GT3_TXOUTCLKPCS_OUT,
    input           GT3_TXPCSRESET_IN,
    input           GT3_TXUSRCLK_IN,
    input           GT3_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT3_GTXTXN_OUT,
    output          GT3_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT3_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT3_TXRESETDONE_OUT,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT4  (X0Y4)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT4_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT4_CPLLFBCLKLOST_OUT,
    output          GT4_CPLLLOCK_OUT,
    input           GT4_CPLLLOCKDETCLK_IN,
    output          GT4_CPLLREFCLKLOST_OUT,
    input           GT4_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT4_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT4_LOOPBACK_IN,
    input   [1:0]   GT4_RXPD_IN,
    input   [1:0]   GT4_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT4_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT4_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT4_RXBYTEISALIGNED_OUT,
    output          GT4_RXBYTEREALIGN_OUT,
    output          GT4_RXCOMMADET_OUT,
    input           GT4_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT4_GTRXRESET_IN,
    output  [15:0]  GT4_RXDATA_OUT,
    output          GT4_RXOUTCLK_OUT,
    input           GT4_RXPCSRESET_IN,
    input           GT4_RXUSRCLK_IN,
    input           GT4_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT4_GTXRXN_IN,
    input           GT4_GTXRXP_IN,
    output          GT4_RXCDRLOCK_OUT,
    output          GT4_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT4_RXBUFRESET_IN,
    output  [2:0]   GT4_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT4_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT4_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT4_TXPRECURSORINV_IN,
    input           GT4_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT4_GTTXRESET_IN,
    input   [15:0]  GT4_TXDATA_IN,
    output          GT4_TXOUTCLK_OUT,
    output          GT4_TXOUTCLKFABRIC_OUT,
    output          GT4_TXOUTCLKPCS_OUT,
    input           GT4_TXPCSRESET_IN,
    input           GT4_TXUSRCLK_IN,
    input           GT4_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT4_GTXTXN_OUT,
    output          GT4_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT4_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT4_TXRESETDONE_OUT,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT5  (X0Y5)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT5_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT5_CPLLFBCLKLOST_OUT,
    output          GT5_CPLLLOCK_OUT,
    input           GT5_CPLLLOCKDETCLK_IN,
    output          GT5_CPLLREFCLKLOST_OUT,
    input           GT5_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT5_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT5_LOOPBACK_IN,
    input   [1:0]   GT5_RXPD_IN,
    input   [1:0]   GT5_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT5_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT5_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT5_RXBYTEISALIGNED_OUT,
    output          GT5_RXBYTEREALIGN_OUT,
    output          GT5_RXCOMMADET_OUT,
    input           GT5_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT5_GTRXRESET_IN,
    output  [15:0]  GT5_RXDATA_OUT,
    output          GT5_RXOUTCLK_OUT,
    input           GT5_RXPCSRESET_IN,
    input           GT5_RXUSRCLK_IN,
    input           GT5_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT5_GTXRXN_IN,
    input           GT5_GTXRXP_IN,
    output          GT5_RXCDRLOCK_OUT,
    output          GT5_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT5_RXBUFRESET_IN,
    output  [2:0]   GT5_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT5_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT5_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT5_TXPRECURSORINV_IN,
    input           GT5_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT5_GTTXRESET_IN,
    input   [15:0]  GT5_TXDATA_IN,
    output          GT5_TXOUTCLK_OUT,
    output          GT5_TXOUTCLKFABRIC_OUT,
    output          GT5_TXOUTCLKPCS_OUT,
    input           GT5_TXPCSRESET_IN,
    input           GT5_TXUSRCLK_IN,
    input           GT5_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT5_GTXTXN_OUT,
    output          GT5_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT5_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT5_TXRESETDONE_OUT,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT6  (X0Y6)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT6_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT6_CPLLFBCLKLOST_OUT,
    output          GT6_CPLLLOCK_OUT,
    input           GT6_CPLLLOCKDETCLK_IN,
    output          GT6_CPLLREFCLKLOST_OUT,
    input           GT6_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT6_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT6_LOOPBACK_IN,
    input   [1:0]   GT6_RXPD_IN,
    input   [1:0]   GT6_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT6_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT6_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT6_RXBYTEISALIGNED_OUT,
    output          GT6_RXBYTEREALIGN_OUT,
    output          GT6_RXCOMMADET_OUT,
    input           GT6_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT6_GTRXRESET_IN,
    output  [15:0]  GT6_RXDATA_OUT,
    output          GT6_RXOUTCLK_OUT,
    input           GT6_RXPCSRESET_IN,
    input           GT6_RXUSRCLK_IN,
    input           GT6_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT6_GTXRXN_IN,
    input           GT6_GTXRXP_IN,
    output          GT6_RXCDRLOCK_OUT,
    output          GT6_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT6_RXBUFRESET_IN,
    output  [2:0]   GT6_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT6_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT6_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT6_TXPRECURSORINV_IN,
    input           GT6_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT6_GTTXRESET_IN,
    input   [15:0]  GT6_TXDATA_IN,
    output          GT6_TXOUTCLK_OUT,
    output          GT6_TXOUTCLKFABRIC_OUT,
    output          GT6_TXOUTCLKPCS_OUT,
    input           GT6_TXPCSRESET_IN,
    input           GT6_TXUSRCLK_IN,
    input           GT6_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT6_GTXTXN_OUT,
    output          GT6_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT6_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT6_TXRESETDONE_OUT,

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT7  (X0Y7)
    //____________________________CHANNEL PORTS________________________________
    //----------------------- Channel - Ref Clock Ports ------------------------
    input           GT7_GTREFCLK0_IN,
    //------------------------------ Channel PLL -------------------------------
    output          GT7_CPLLFBCLKLOST_OUT,
    output          GT7_CPLLLOCK_OUT,
    input           GT7_CPLLLOCKDETCLK_IN,
    output          GT7_CPLLREFCLKLOST_OUT,
    input           GT7_CPLLRESET_IN,
    //----------------------------- Eye Scan Ports -----------------------------
    output          GT7_EYESCANDATAERROR_OUT,
    //---------------------- Loopback and Powerdown Ports ----------------------
    input   [2:0]   GT7_LOOPBACK_IN,
    input   [1:0]   GT7_RXPD_IN,
    input   [1:0]   GT7_TXPD_IN,
    //----------------------------- Receive Ports ------------------------------
    input           GT7_RXUSERRDY_IN,
    //----------------- Receive Ports - Clock Correction Ports -----------------
    output  [1:0]   GT7_RXCLKCORCNT_OUT,
    //------------- Receive Ports - Comma Detection and Alignment --------------
    output          GT7_RXBYTEISALIGNED_OUT,
    output          GT7_RXBYTEREALIGN_OUT,
    output          GT7_RXCOMMADET_OUT,
    input           GT7_RXSLIDE_IN,
    //----------------- Receive Ports - RX Data Path interface -----------------
    input           GT7_GTRXRESET_IN,
    output  [15:0]  GT7_RXDATA_OUT,
    output          GT7_RXOUTCLK_OUT,
    input           GT7_RXPCSRESET_IN,
    input           GT7_RXUSRCLK_IN,
    input           GT7_RXUSRCLK2_IN,
    //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
    input           GT7_GTXRXN_IN,
    input           GT7_GTXRXP_IN,
    output          GT7_RXCDRLOCK_OUT,
    output          GT7_RXELECIDLE_OUT,
    //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
    input           GT7_RXBUFRESET_IN,
    output  [2:0]   GT7_RXBUFSTATUS_OUT,
    //---------------------- Receive Ports - RX PLL Ports ----------------------
    output          GT7_RXRESETDONE_OUT,
    //------------ Receive Ports - RX Pipe Control for PCI Express -------------
    output          GT7_RXVALID_OUT,
    //----------------------------- Transmit Ports -----------------------------
    input           GT7_TXPRECURSORINV_IN,
    input           GT7_TXUSERRDY_IN,
    //---------------- Transmit Ports - TX Data Path interface -----------------
    input           GT7_GTTXRESET_IN,
    input   [15:0]  GT7_TXDATA_IN,
    output          GT7_TXOUTCLK_OUT,
    output          GT7_TXOUTCLKFABRIC_OUT,
    output          GT7_TXOUTCLKPCS_OUT,
    input           GT7_TXPCSRESET_IN,
    input           GT7_TXUSRCLK_IN,
    input           GT7_TXUSRCLK2_IN,
    //-------------- Transmit Ports - TX Driver and OOB signaling --------------
    output          GT7_GTXTXN_OUT,
    output          GT7_GTXTXP_OUT,
    //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
    output  [1:0]   GT7_TXBUFSTATUS_OUT,
    //--------------------- Transmit Ports - TX PLL Ports ----------------------
    output          GT7_TXRESETDONE_OUT



);

//***************************** Wire Declarations *****************************

    // ground and vcc signals
    wire            tied_to_ground_i;
    wire    [63:0]  tied_to_ground_vec_i;
    wire            tied_to_vcc_i;
    wire    [63:0]  tied_to_vcc_vec_i;


    wire            gt0_qpllclk_i;
    wire            gt0_qpllrefclk_i;

    wire            gt1_qpllclk_i;
    wire            gt1_qpllrefclk_i;

    wire            gt2_qpllclk_i;
    wire            gt2_qpllrefclk_i;

    wire            gt3_qpllclk_i;
    wire            gt3_qpllrefclk_i;

    wire            gt4_qpllclk_i;
    wire            gt4_qpllrefclk_i;

    wire            gt5_qpllclk_i;
    wire            gt5_qpllrefclk_i;

    wire            gt6_qpllclk_i;
    wire            gt6_qpllrefclk_i;

    wire            gt7_qpllclk_i;
    wire            gt7_qpllrefclk_i;

         
//********************************* Main Body of Code**************************

    assign tied_to_ground_i             = 1'b0;
    assign tied_to_ground_vec_i         = 64'h0000000000000000;
    assign tied_to_vcc_i                = 1'b1;
    assign tied_to_vcc_vec_i            = 64'hffffffffffffffff;


      
//------------------------- GT Instances  -------------------------------
    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT0  (X0Y0)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt0_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT0_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT0_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT0_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT0_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT0_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT0_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT0_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT0_LOOPBACK_IN),
        .RXPD_IN                        (GT0_RXPD_IN),
        .TXPD_IN                        (GT0_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT0_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT0_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT0_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT0_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT0_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT0_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT0_GTRXRESET_IN),
        .RXDATA_OUT                     (GT0_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT0_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT0_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT0_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT0_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT0_GTXRXN_IN),
        .GTXRXP_IN                      (GT0_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT0_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT0_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT0_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT0_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT0_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT0_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT0_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT0_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT0_GTTXRESET_IN),
        .TXDATA_IN                      (GT0_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT0_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT0_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT0_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT0_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT0_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT0_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT0_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT0_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT0_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT0_TXRESETDONE_OUT)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT1  (X0Y1)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt1_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT1_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT1_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT1_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT1_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT1_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT1_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT1_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT1_LOOPBACK_IN),
        .RXPD_IN                        (GT1_RXPD_IN),
        .TXPD_IN                        (GT1_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT1_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT1_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT1_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT1_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT1_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT1_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT1_GTRXRESET_IN),
        .RXDATA_OUT                     (GT1_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT1_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT1_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT1_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT1_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT1_GTXRXN_IN),
        .GTXRXP_IN                      (GT1_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT1_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT1_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT1_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT1_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT1_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT1_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT1_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT1_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT1_GTTXRESET_IN),
        .TXDATA_IN                      (GT1_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT1_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT1_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT1_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT1_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT1_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT1_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT1_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT1_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT1_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT1_TXRESETDONE_OUT)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT2  (X0Y2)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt2_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT2_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT2_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT2_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT2_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT2_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT2_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT2_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT2_LOOPBACK_IN),
        .RXPD_IN                        (GT2_RXPD_IN),
        .TXPD_IN                        (GT2_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT2_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT2_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT2_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT2_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT2_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT2_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT2_GTRXRESET_IN),
        .RXDATA_OUT                     (GT2_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT2_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT2_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT2_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT2_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT2_GTXRXN_IN),
        .GTXRXP_IN                      (GT2_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT2_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT2_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT2_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT2_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT2_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT2_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT2_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT2_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT2_GTTXRESET_IN),
        .TXDATA_IN                      (GT2_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT2_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT2_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT2_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT2_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT2_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT2_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT2_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT2_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT2_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT2_TXRESETDONE_OUT)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT3  (X0Y3)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt3_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT3_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT3_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT3_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT3_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT3_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT3_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT3_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT3_LOOPBACK_IN),
        .RXPD_IN                        (GT3_RXPD_IN),
        .TXPD_IN                        (GT3_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT3_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT3_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT3_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT3_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT3_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT3_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT3_GTRXRESET_IN),
        .RXDATA_OUT                     (GT3_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT3_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT3_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT3_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT3_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT3_GTXRXN_IN),
        .GTXRXP_IN                      (GT3_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT3_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT3_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT3_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT3_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT3_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT3_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT3_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT3_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT3_GTTXRESET_IN),
        .TXDATA_IN                      (GT3_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT3_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT3_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT3_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT3_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT3_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT3_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT3_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT3_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT3_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT3_TXRESETDONE_OUT)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT4  (X0Y4)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt4_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT4_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT4_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT4_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT4_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT4_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT4_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT4_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT4_LOOPBACK_IN),
        .RXPD_IN                        (GT4_RXPD_IN),
        .TXPD_IN                        (GT4_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT4_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT4_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT4_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT4_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT4_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT4_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT4_GTRXRESET_IN),
        .RXDATA_OUT                     (GT4_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT4_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT4_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT4_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT4_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT4_GTXRXN_IN),
        .GTXRXP_IN                      (GT4_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT4_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT4_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT4_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT4_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT4_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT4_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT4_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT4_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT4_GTTXRESET_IN),
        .TXDATA_IN                      (GT4_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT4_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT4_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT4_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT4_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT4_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT4_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT4_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT4_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT4_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT4_TXRESETDONE_OUT)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT5  (X0Y5)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt5_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT5_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT5_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT5_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT5_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT5_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT5_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT5_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT5_LOOPBACK_IN),
        .RXPD_IN                        (GT5_RXPD_IN),
        .TXPD_IN                        (GT5_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT5_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT5_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT5_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT5_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT5_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT5_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT5_GTRXRESET_IN),
        .RXDATA_OUT                     (GT5_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT5_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT5_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT5_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT5_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT5_GTXRXN_IN),
        .GTXRXP_IN                      (GT5_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT5_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT5_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT5_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT5_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT5_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT5_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT5_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT5_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT5_GTTXRESET_IN),
        .TXDATA_IN                      (GT5_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT5_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT5_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT5_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT5_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT5_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT5_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT5_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT5_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT5_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT5_TXRESETDONE_OUT)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT6  (X0Y6)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt6_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT6_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT6_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT6_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT6_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT6_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT6_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT6_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT6_LOOPBACK_IN),
        .RXPD_IN                        (GT6_RXPD_IN),
        .TXPD_IN                        (GT6_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT6_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT6_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT6_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT6_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT6_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT6_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT6_GTRXRESET_IN),
        .RXDATA_OUT                     (GT6_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT6_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT6_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT6_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT6_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT6_GTXRXN_IN),
        .GTXRXP_IN                      (GT6_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT6_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT6_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT6_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT6_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT6_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT6_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT6_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT6_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT6_GTTXRESET_IN),
        .TXDATA_IN                      (GT6_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT6_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT6_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT6_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT6_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT6_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT6_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT6_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT6_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT6_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT6_TXRESETDONE_OUT)

    );

    //_________________________________________________________________________
    //_________________________________________________________________________
    //GT7  (X0Y7)

    ROCKETIO_WRAPPER_TILE_GT #
    (
        // Simulation attributes
        .GT_SIM_GTRESET_SPEEDUP   (WRAPPER_SIM_GTRESET_SPEEDUP)
        
    )
    gt7_ROCKETIO_WRAPPER_TILE_i
    (
        //----------------------- Channel - Ref Clock Ports ------------------------
        .GTREFCLK0_IN                   (GT7_GTREFCLK0_IN),
        //------------------------------ Channel PLL -------------------------------
        .CPLLFBCLKLOST_OUT              (GT7_CPLLFBCLKLOST_OUT),
        .CPLLLOCK_OUT                   (GT7_CPLLLOCK_OUT),
        .CPLLLOCKDETCLK_IN              (GT7_CPLLLOCKDETCLK_IN),
        .CPLLREFCLKLOST_OUT             (GT7_CPLLREFCLKLOST_OUT),
        .CPLLRESET_IN                   (GT7_CPLLRESET_IN),
        //----------------------------- Eye Scan Ports -----------------------------
        .EYESCANDATAERROR_OUT           (GT7_EYESCANDATAERROR_OUT),
        //---------------------- Loopback and Powerdown Ports ----------------------
        .LOOPBACK_IN                    (GT7_LOOPBACK_IN),
        .RXPD_IN                        (GT7_RXPD_IN),
        .TXPD_IN                        (GT7_TXPD_IN),
        //----------------------------- Receive Ports ------------------------------
        .RXUSERRDY_IN                   (GT7_RXUSERRDY_IN),
        //----------------- Receive Ports - Clock Correction Ports -----------------
        .RXCLKCORCNT_OUT                (GT7_RXCLKCORCNT_OUT),
        //------------- Receive Ports - Comma Detection and Alignment --------------
        .RXBYTEISALIGNED_OUT            (GT7_RXBYTEISALIGNED_OUT),
        .RXBYTEREALIGN_OUT              (GT7_RXBYTEREALIGN_OUT),
        .RXCOMMADET_OUT                 (GT7_RXCOMMADET_OUT),
        .RXSLIDE_IN                     (GT7_RXSLIDE_IN),
        //----------------- Receive Ports - RX Data Path interface -----------------
        .GTRXRESET_IN                   (GT7_GTRXRESET_IN),
        .RXDATA_OUT                     (GT7_RXDATA_OUT),
        .RXOUTCLK_OUT                   (GT7_RXOUTCLK_OUT),
        .RXPCSRESET_IN                  (GT7_RXPCSRESET_IN),
        .RXUSRCLK_IN                    (GT7_RXUSRCLK_IN),
        .RXUSRCLK2_IN                   (GT7_RXUSRCLK2_IN),
        //----- Receive Ports - RX Driver,OOB signalling,Coupling and Eq.,CDR ------
        .GTXRXN_IN                      (GT7_GTXRXN_IN),
        .GTXRXP_IN                      (GT7_GTXRXP_IN),
        .RXCDRLOCK_OUT                  (GT7_RXCDRLOCK_OUT),
        .RXELECIDLE_OUT                 (GT7_RXELECIDLE_OUT),
        //------ Receive Ports - RX Elastic Buffer and Phase Alignment Ports -------
        .RXBUFRESET_IN                  (GT7_RXBUFRESET_IN),
        .RXBUFSTATUS_OUT                (GT7_RXBUFSTATUS_OUT),
        //---------------------- Receive Ports - RX PLL Ports ----------------------
        .RXRESETDONE_OUT                (GT7_RXRESETDONE_OUT),
        //------------ Receive Ports - RX Pipe Control for PCI Express -------------
        .RXVALID_OUT                    (GT7_RXVALID_OUT),
        //----------------------------- Transmit Ports -----------------------------
        .TXPRECURSORINV_IN              (GT7_TXPRECURSORINV_IN),
        .TXUSERRDY_IN                   (GT7_TXUSERRDY_IN),
        //---------------- Transmit Ports - TX Data Path interface -----------------
        .GTTXRESET_IN                   (GT7_GTTXRESET_IN),
        .TXDATA_IN                      (GT7_TXDATA_IN),
        .TXOUTCLK_OUT                   (GT7_TXOUTCLK_OUT),
        .TXOUTCLKFABRIC_OUT             (GT7_TXOUTCLKFABRIC_OUT),
        .TXOUTCLKPCS_OUT                (GT7_TXOUTCLKPCS_OUT),
        .TXPCSRESET_IN                  (GT7_TXPCSRESET_IN),
        .TXUSRCLK_IN                    (GT7_TXUSRCLK_IN),
        .TXUSRCLK2_IN                   (GT7_TXUSRCLK2_IN),
        //-------------- Transmit Ports - TX Driver and OOB signaling --------------
        .GTXTXN_OUT                     (GT7_GTXTXN_OUT),
        .GTXTXP_OUT                     (GT7_GTXTXP_OUT),
        //--------- Transmit Ports - TX Elastic Buffer and Phase Alignment ---------
        .TXBUFSTATUS_OUT                (GT7_TXBUFSTATUS_OUT),
        //--------------------- Transmit Ports - TX PLL Ports ----------------------
        .TXRESETDONE_OUT                (GT7_TXRESETDONE_OUT)

    );



endmodule

    
