//=============================================
// PSTBR Defines
//=============================================

//------------------------
// PL Interface
//------------------------
`define PCIE6_CX_REMOTE_LOOKUPID_WD 14
`define PCIE6_CX_TAG_SIZE 14
`define PCIE6_FLT_Q_ATTR_WIDTH 3
`define PCIE6_FLT_Q_ADDR_WIDTH 64
`define PCIE6_CX_NPRFX 3
`define PCIE6_CX_NVC 4'd1
`define PCIE6_CX_HCRD_WD 12
`define PCIE6_CX_DCRD_WD 16

`define PCIE6_PSTBR_PL_RX_SLOT_NUM 3
`define PCIE6_PSTBR_PL_RX_SLOT_WIDTH $bits(pstbr_rtrgt1_np_no_data_hdr_t)*3
`define PCIE6_PSTBR_PL_RX_DATA_WIDTH `PCIE6_PSTBR_PL_RX_SLOT_WIDTH*`PCIE6_PSTBR_PL_RX_SLOT_NUM 
`define PCIE6_PSTBR_PL_RX_DATA_PARITY_WIDTH 42
`define PCIE6_PSTBR_PL_RX_START_WIDTH `PCIE6_PSTBR_PL_RX_SLOT_NUM
`define PCIE6_PSTBR_PL_RX_STARTPTR_WIDTH 2
`define PCIE6_PSTBR_PL_RX_END_WIDTH `PCIE6_PSTBR_PL_RX_SLOT_NUM
`define PCIE6_PSTBR_PL_RX_ENDPTR_WIDTH (`PCIE6_PSTBR_PL_RX_STARTPTR_WIDTH+4)
`define PCIE6_PSTBR_PL_RX_STARTTYPE_WIDTH 2
`define PCIE6_PSTBR_PL_RX_STARTNPINFO_WIDTH 3
`define PCIE6_PSTBR_PL_RX_END_ERROR_WIDTH 9
`define PCIE6_PSTBR_PL_RX_CREDIT_BUS_WIDTH 3

`define PCIE6_PSTBR_PL_TX_SLOT_NUM 3
`define PCIE6_PSTBR_PL_TX_SLOT_WIDTH $bits(pstbr_pl_tx_xali_np_no_data_hdr_t)*3
`define PCIE6_PSTBR_PL_TX_DATA_WIDTH `PCIE6_PSTBR_PL_TX_SLOT_WIDTH*`PCIE6_PSTBR_PL_TX_SLOT_NUM
`define PCIE6_PSTBR_PL_TX_DATA_PARITY_WIDTH 40
`define PCIE6_PSTBR_PL_TX_START_WIDTH `PCIE6_PSTBR_PL_TX_SLOT_NUM
`define PCIE6_PSTBR_PL_TX_STARTPTR_WIDTH 2
`define PCIE6_PSTBR_PL_TX_END_WIDTH `PCIE6_PSTBR_PL_TX_SLOT_NUM
`define PCIE6_PSTBR_PL_TX_ENDPTR_WIDTH (`PCIE6_PSTBR_PL_TX_STARTPTR_WIDTH+4)
`define PCIE6_PSTBR_PL_TX_STARTTYPE_WIDTH 2
`define PCIE6_PSTBR_PL_TX_STARTNPINFO_WIDTH 3
`define PCIE6_PSTBR_PL_TX_END_ERROR_WIDTH 9
`define PCIE6_PSTBR_PL_TX_CREDIT_BUS_WIDTH 3

//------------------------
// PSTBR Async FIFOS
//------------------------
`define PCIE6_PSTBR_SNPS_DATA_WIDTH 512
`define PCIE6_PSTBR_PL_RX_CRDT_CNTR_WIDTH 8
`define PCIE6_PSTBR_PL_TX_CRDT_CNTR_WIDTH 8
`define PCIE6_CX_NVFUNC_WD 9
`define PCIE6_CX_NFUNC_WD 3
`ifndef PL_MUX_SEL
    `define PL_MUX_SEL

    `define  STRM               4'b1110
    `define  CXL                4'b1101
    `define  AXI                4'b1001
    `define  DEFAULT            1'b0
    `define  CPM_MODE           1'b1

`endif
